version: '3.8'

services:
  token-transfer-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:3000"
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
